name: 'Run Salesforce Code Analyzer'
description:
  'Scans your code for violations using Salesforce Code Analyzer, uploads results as an artifact, and creates a job
  summary.'
author: 'Salesforce Code Analyzer Team'

branding:
  icon: 'play'
  color: 'gray-dark'

inputs:
  run-arguments:
    description: |-
      Specifies the flags passed to the `code-analyzer run` command.
      Default: "--view detail --output-file sfca_results.json"

      For a full list of valid flags for the `code-analyzer run` command, see the [code-analyzer Command Reference](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_code-analyzer_commands_unified.htm).

      The stdout text from the `code-analyzer run` command is written to the GitHub workflow run logs.

      Each output file specified by a `--output-file` (or `-f`) flag is included in the ZIP archive [GitHub workflow run artifact](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/downloading-workflow-artifacts) for you to download.
    required: false
    default: '--view detail --output-file sfca_results.json'
  results-artifact-name:
    description: |-
      Specifies the name of the ZIP archive [GitHub workflow run artifact](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/downloading-workflow-artifacts) where the results output files are uploaded.
      Default: "salesforce-code-analyzer-results"
    required: false
    default: 'salesforce-code-analyzer-results'
  github-token:
    description: |-
      When this action is run against a pull request, you can provide a Github token, which is used to create a review of the pull request. The review specifies how many violations were found (both in the project as a whole and in changed files) and links to the action summary page.

      This token must have write permissions for pull requests.
    required: false

outputs:
  exit-code:
    description: The Salesforce Code Analyzer execution exit code.
  num-violations:
    description: The total number of violations found.
  num-sev1-violations:
    description: The number of Critical (1) severity violations found.
  num-sev2-violations:
    description: The number of High (2) severity violations found.
  num-sev3-violations:
    description: The number of Medium (3) severity violations found.
  num-sev4-violations:
    description: The number of Low (4) severity violations found.
  num-sev5-violations:
    description: The number of Info (5) severity violations found.
  review-id:
    description: If this action created a pull request review, this is its ID.

runs:
  using: node20
  main: dist/index.js
